### ISSUE TITLE
Add optional command line argument to support strong name signing after the modification

### ISSUE THREAD

**Issue by dee-see** [qerub/ReplaceEmbeddedAssemblyResource#2]
It would be nice if we could supply the strong name key pair and let Mono.Cecil resign the assembly after modifying the resources.

I'm willing to do the modification if this is still maintained and you think it's a good idea!

**Comment by qerub** [comment]
Sure, that's a good idea! I don't use this program anymore myself, but I'm happy to merge a patch that adds support for this.

**Comment by qerub** [comment]
Resolved with #3. Closing.
